version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: sophyfarm-database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: rendimiento_sophyfarm_db
    ports:
      - "5433:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
